image: nikolaik/python-nodejs:latest

before_script:
  - pip install mkdocs
  - pip install mkdocs-material

pages:
  script:
  - npm i -g yarn
  - yarn
  - yarn docs
  - yarn build
  - mkdocs build
  - mv site public
  - mv index.html public/game.html
  - rm -rf public/source
  - mv docs/ts public/source
  - mv dist public/dist
  - mv assets/* public/assets
  - mv src public/src
  - mv menu.json public/menu.json
  artifacts:
    paths:
    - public
  only:
  - docs
