image: nikolaik/python-nodejs:latest

before_script:
  - pip install mkdocs
  - pip install mkdocs-material
  - pip install beautifulsoup4
  - pip install mkdocs-mermaid-plugin

pages:
  script:
  - npm i -g yarn
  - yarn
  - yarn docs
  - yarn build
  - mkdocs build
  - mv site public
  - mv index.html public/game.html
  - mv dist public/dist
  - mv assets public/assets
  artifacts:
    paths:
    - public
  only:
  - master

