image: nikolaik/python-nodejs:latest

before_script:
  - pip install mkdocs
  - pip install mkdocs-material

pages:
  script:
  - npm i -g yarn
  - yarn
  - yarn docs
  - yarn build
  - mkdocs build
  - mv site public
  - mv index.html public/game.html
  - mv dist public/dist
  artifacts:
    paths:
    - public
  only:
  - master

