site_name: Go Up
theme:
  name: 'material'
  palette: 
    primary: light blue
  logo:
    icon: 'backup'
  feature:
    tabs: true
markdown_extensions:
  - codehilite
repo_url: 'https://gitlab.com/byhemechi/ballmouse'
edit_uri: ""