site_name: ballmouse docs
site_description: The docs for a collection of Games
site_author: George Fischer and Joon Suh
site_url: https://splorge.space/

copyright: 'somebody once told me the world is gonna roll me'

theme:
  name: 'material'
  palette: 
    primary: deep orange
  logo:
    icon: 'gamepad'

  favicon: /coolguy.png
  feature:
    tabs: true

extra_javascript:
    - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
    - javascripts/hl.js
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'


markdown_extensions:
  - toc:
      permalink: 🔗
  - codehilite
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.details
  - footnotes
  - admonition
  - pymdownx.arithmatex
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde
