site_name: "Bob Katter: Dab of Destiny"
theme:
  name: 'material'
  palette: 
    primary: white
  logo:
    icon: 'backup'
  feature:
    tabs: true
repo_url: 'https://gitlab.com/byhemechi/ballmouse'
edit_uri: ""

extra_css:
  - //cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.8/styles/default.min.css

extra_javascript:
    - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js