site_name: "Bob Katter: Dab of Destiny"
theme:
  name: 'material'
  palette: 
    primary: white
  logo:
    icon: 'backup'
  feature:
    tabs: true
markdown_extensions:
  - codehilite
repo_url: 'https://gitlab.com/byhemechi/ballmouse'
edit_uri: ""