site_name: "Bob Katter: Dab of Destiny"
theme:
  name: 'material'
  palette: 
    primary: white
  logo:
    icon: 'backup'
  feature:
    tabs: true
repo_url: 'https://gitlab.com/byhemechi/ballmouse'
edit_uri: ""

extra_javascript:
    - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
    - /hl.js

markdown_extensions:
  - toc:
      permalink: 🔗
  - codehilite:
      linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.details
  - footnotes
  - admonition