site_name: ballmouse docs
site_description: The docs for a collection of Games
site_author: George Fischer and Joon Suh
site_url: https://splorge.space/

copyright: 'If you ever feel that you need to use content from this site elsewhere you might have some problems other than copyright'

theme:
  name: 'material'
  palette: 
    primary: white
  logo:
    icon: 'gamepad'

  favicon: /coolguy.png
  feature:
    tabs: true
repo_url: 'https://gitlab.com/byhemechi/ballmouse'
repo_name: byhemechi/ballmouse
edit_uri: ""

extra_javascript:
    - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
    - /hl.js

markdown_extensions:
  - toc:
      permalink: 🔗
  - codehilite
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.details
  - footnotes
  - admonition