apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- httproute.yml
images:
- name: ballmouse
labels:
- includeSelectors: true
  pairs:
    app: ballmouse
